-- Add example_questions column to notebooks table
ALTER TABLE public.notebooks ADD COLUMN IF NOT EXISTS example_questions text[] DEFAULT '{}';

-- Add comment explaining the column
COMMENT ON COLUMN public.notebooks.example_questions IS 'Array of example questions generated by AI for this notebook';
